---
- name: flask | configure alerts
  connection: local
  hosts: localhost
  gather_facts: false
  vars:
    tags:
      - funnel
      - flask
    pagerduty_service: 7ac2bc6607a646e896d574e683d91bff
    emails:
      - oncue.monitoring@one.verizon.com
      - timothy.m.perrett@one.verizon.com
    environments:
      imdev:
        actions:
          critical:
            - kind: email
              recipients: "{{ emails }}"
          warning:
            - kind: email
              recipients: "{{ emails }}"
      imqa:
        actions:
          critical:
            - kind: email
              recipients: "{{ emails }}"
          warning:
            - kind: email
              recipients: "{{ emails }}"
      improd:
        actions:
          critical:
            - kind: pagerduty
              service: "{{ pagerduty_service }}"
            - kind: email
              recipients: "{{ emails }}"
          warning:
            - kind: pagerduty
              service: "{{ pagerduty_service }}"
            - kind: email
              recipients: "{{ emails }}"
  tasks:
    - gong:
        state: present
        account: "{{ application_environment }}"
        namespace: "{{ application_name }}"
        window: "{{ item.window }}"
        name: "{{ item.name }}"
        query: "cluster: {{ application_name }}* AND name:({{ item.filter }})"
        tags: "{{ tags }}"
        aggregations:
          target:
            op: "{{ item.aggregation }}"
            field: "{{ item.field }}"
        critical: "{{ item.critical }}"
        warning: "{{ item.warning }}"
        actions: "{{ environments[application_environment].actions }}"
      with_items:
        - name: low-disk-space
          window: 10 minutes
          filter: system.file_system./.use_percent
          field: numeric.mean
          critical: "!(target < 0.9)"
          warning: "!(target < 0.8)"
          aggregation: max
        - name: high-cpu
          window: 10 minutes
          filter: system.cpu.aggregate.usage.combined
          field: numeric.mean
          critical: target >= 0.95
          warning: target >= 0.90
          aggregation: avg
        # purpose of this alert is to provide a negative check
        # and ensure that the datapoints do not drop below a
        # known reasonable threshold. Anything less than a
        # couple thousand datapoints a minute means the flasks
        # dont have appropriate workload.
        - name: low-mirror-datapoints
          window: 10 minutes
          filter: mirror.datapoints
          field: counter
          critical: target < 500
          warning: target < 1000
          aggregation: avg

