---
- name: flask | configure alerts
  connection: local
  hosts: localhost
  gather_facts: false
  tasks:
    - name: flask | should not have low disk space
      gong:
        state: "present"
        account: "{{ application_environment }}"
        namespace: "{{ application_name }}"
        window: 10 minutes
        name: low-disk-space
        query: "cluster: flask*"
        critical: "!(disk < 0.9)"
        warning: "!(disk < 0.8)"
        tags:
          - funnel
          - flask
        aggregations:
          disk:
            op: min
            field: "file_system.%2F.use_percent.numeric.mean"
        actions:
          critical:
            - kind: email
              recipients:
                - oncue.monitoring@one.verizon.com
          warning:
            - kind: email
              recipients:
                - oncue.monitoring@one.verizon.com

    - name: flask | should not peg its cpu for 10 minutes
      gong:
        state: present
        account: "{{ application_environment }}"
        namespace: "{{ application_name }}"
        window: 10 minutes
        name: high-cpu
        query: "cluster: flask*"
        critical: cpu >= 0.95
        warning: cpu >= 0.90
        tags:
          - funnel
          - flask
        aggregations:
          cpu:
            op: avg
            field: cpu.aggregate.usage.combined.numeric.mean
        actions:
          critical:
            - kind: email
              recipients:
                - oncue.monitoring@one.verizon.com
          warning:
            - kind: email
              recipients:
                - oncue.monitoring@one.verizon.com

    # purpose of this alert is to provide a negative check
    # and ensure that the datapoints do not drop below a
    # known reasonable threshold. Anything less than a
    # couple thousand datapoints a minute means the flasks
    # dont have appropriate workload.
    - name: flask | should not have low mirroring datapoints
      gong:
        state: present
        account: "{{ application_environment }}"
        namespace: "{{ application_name }}"
        window: 10 minutes
        name: low-mirror-datapoints
        query: "cluster: flask*"
        critical: "datapoints > 500"
        warning: "datapoints > 1000"
        tags:
          - funnel
          - flask
        aggregations:
          datapoints:
            op: max
            field: mirror.datapoints.counter
        actions:
          critical:
            - kind: email
              recipients:
                - oncue.monitoring@one.verizon.com
          warning:
            - kind: email
              recipients:
                - oncue.monitoring@one.verizon.com


