---
- name: flask | deploy cluster
  hosts: all
  connection: local
  gather_facts: false
  vars:
    environments:
      imdev:
        machine_class: m4.xlarge
        asg_min: "3"
        asg_max: "5"
      imqa:
        machine_class: m4.2xlarge
        asg_min: "5"
        asg_max: "8"
      improd:
        machine_class: m4.2xlarge
        asg_min: "10"
        asg_max: "25"
  roles:
    - { role: launcher,
        amazon_cf_template: "flask.template",
        amazon_instance_type: "{{ environments[deployment_environment].machine_class }}",
        asg_desired:  "{{ environments[deployment_environment].asg_min }}",
        asg_min_size: "{{ environments[deployment_environment].asg_min }}",
        asg_max_size: "{{ environments[deployment_environment].asg_max }}"
      }
