---
- name: chemist | create image
  hosts: all
  gather_facts: false
  user: ec2-user
  roles:
    - role: application
      loggers:
        - name: intelmedia.ws
          level: INFO
        - name: oncue.svc
          level: DEBUG
        - name: funnel
          level: DEBUG
  tasks:
    - name: chemist | override configuration file
      sudo: yes
      template: >
        src=templates/chemist.cfg.j2
        dest=/usr/share/oncue/etc/chemist.cfg
        owner=root group=root mode=0644
