---
- name: chemist | create image
  hosts: all
  gather_facts: false
  user: ec2-user
  roles:
    - application
  tasks:
    - name: chemist | override configuration file
      sudo: yes
      template: >
        src=templates/chemist.cfg.j2
        dest=/usr/share/oncue/etc/chemist.cfg
        owner=root group=root mode=0644

    - name: chemist | add custom nginx configuration
      sudo: yes
      template: >
        src=templates/chemist.conf.j2
        dest=/etc/nginx/conf.d/chemist.conf
        owner=root group=root mode=0644

    - name: chemist | remove the 2-way ssl conf
      sudo: yes
      file: >
        path={{ item.path }}
        state=absent
      with_items:
      - { path: '/etc/nginx/conf.d/internal.conf' }
      - { path: '/etc/nginx/conf.d/monitoring.conf' }

    - name: chemist | restart chemist service
      sudo: yes
      service: name=nginx state=restarted
